### Obtener todos los turnos
GET http://localhost:3001/turnos

### Obtener un turno por su ID
GET http://localhost:3001/turnos/129

### Crear un nuevo turno
POST http://localhost:3001/turnos
Content-Type: application/json

{
  "id_agenda_base": 1,
  "id_paciente": 1,
  "id_estado_turno": 1,
  "fecha": "2024-10-17",
  "horario_inicio": "09:00:00",
  "horario_fin": "10:00:00",
  "motivo_consulta": "Consulta inicial"
}

### Actualizar un turno
PATCH http://localhost:3001/turnos/1
Content-Type: application/json

{
  "motivo_consulta": "Consulta de seguimiento"
}

### Eliminar un turno
DELETE http://localhost:3001/turnos/1

### Obtener turnos por fecha
GET http://localhost:3001/turnos/fecha/2024-10-17

### Obtener turnos por paciente
GET http://localhost:3001/turnos/paciente/1

### Obtener turnos por estado de turno
GET http://localhost:3001/turnos/estado/1

### Obtener turnos por motivo de consulta
GET http://localhost:3001/turnos/motivo/seguimiento
