### Obtener todas las agendas base activas
GET http://localhost:3001/agenda_base

### Obtener una agenda base por su ID
GET http://localhost:3001/agenda_base/1

### Crear una agenda base
POST http://localhost:3001/agenda_base
Content-Type: application/json

{
  "id_sucursal": 1,
  "estado": 1,
  "id_estado_agenda": 1,
  "id_clasificacion": 2,
  "duracion_turno": 30,
  "sobreturnos_maximos": 2,
  "matricula": "123456"
}

### Actualizar parcialmente una agenda base
PATCH http://localhost:3001/agenda_base/1
Content-Type: application/json

{
  "duracion_turno": 45,
  "sobreturnos_maximos": 3
}

### Desactivar una agenda base
DELETE http://localhost:3001/agenda_base/1

### Activar una agenda base
PATCH http://localhost:3001/agenda_base/1/activate

### Obtener agendas por matrícula
GET http://localhost:3001/agenda_base/matricula/123456

### Obtener agendas por estado de agenda
GET http://localhost:3001/agenda_base/estado/2

### Obtener agendas por id_sucursal
GET http://localhost:3001/agenda_base/sucursal/1

### Obtener todas las id_sucursal distintas
GET http://localhost:3001/agenda_base/sucursales

### Obtener agendas por combinación de sucursal y clasificación
GET http://localhost:3001/agenda_base/sucursal/1/clasificacion/2
