### Obtener todos los roles
GET http://localhost:3001/roles

### Obtener un rol por su id
GET http://localhost:3001/roles/2

### Crear un rol
POST http://localhost:3001/roles
Content-Type: application/json

{
    "nombre": "Admin",
    "descripcion": "Administrador del sistema"
}


### eliminar un rol
DELETE http://localhost:3001/roles/1

### Actualizar un rol
PATCH http://localhost:3001/roles/1/update
Content-Type: application/json

{
  "descripcion": "probando funcionamiento parcial"
}