### Obtener todos los roles
GET http://localhost:3001/roles

### Obtener un rol por su id
GET http://localhost:3001/roles/2

### Crear un rol
POST http://localhost:3001/roles
Content-Type: application/json

{
    "nombre": "prueba",
    "descripcion": "probaando crud"
}


### eliminar un rol
DELETE http://localhost:3001/roles/5

### Actualizar un rol
PATCH http://localhost:3001/roles/6/update
Content-Type: application/json

{
  "descripcion": "probando 123456"
}