### Obtener todos los profesionales
GET http://localhost:3001/profesionales

### Obtener un profesional por su id
GET http://localhost:3001/profesionales/2

### Crear un profesional
POST http://localhost:3001/profesionales
Content-Type: application/json

{
  "id_usuario": 4
  
}

### Desactivar un profesional
DELETE http://localhost:3001/profesionales/1

### Activar un profesional
PATCH  http://localhost:3001/profesionales/1/activate

### Actualizar un profesional
PATCH http://localhost:3001/profesionales/7/update
Content-Type: application/json

{
  "nombre": "Juana"
}