### Obtener todas las obras sociales
GET http://localhost:3001/obra_social

### Obtener una obra social por su id
GET http://localhost:3001/obra_social/2

### Crear una obra social
POST http://localhost:3001/obra_social
Content-Type: application/json

{
  "nombre": "probando"
  
}

### Desactivar una obra social
DELETE http://localhost:3001/obra_social/6

### Activar una obra social
PATCH  http://localhost:3001/obra_social/6/activate

### Actualizar una obra social
PATCH http://localhost:3001/obra_social/6/update
Content-Type: application/json

{
  "nombre": "PRUEBA"
 
}