### Obtener todos los pacientes
GET http://localhost:3001/pacientes

### Obtener un paciente por su ID
GET http://localhost:3001/pacientes/2

### Crear un paciente
POST http://localhost:3001/pacientes
Content-Type: application/json

{
 "tiene_obra_social": "1",
  "id_usuario": 2
}

### Desactivar un paciente
DELETE http://localhost:3001/pacientes/4

### Activar un paciente
PATCH http://localhost:3001/pacientes/3/activate

### Actualizar parcialmente un paciente
PATCH http://localhost:3001/pacientes/2/update
Content-Type: application/json

{
  "tiene_obra_social": "0"
}

### Obtener pacientes por obra social
GET http://localhost:3001/pacientes/obra_social/1

### Obtener pacientes por usuario
GET http://localhost:3001/pacientes/usuario/2

### Crear un profesional con usuario y especialidades
POST http://localhost:3001/pacientes/users
Content-Type: application/json

{
  "nombre_usuario": "Pedrito",
  "nombre": "Pedrito",
  "contraseña": "Pedrito",
  "apellido": "Pedrito",
  "dni": "12345699",
  "telefono": "12345678",
  "direccion": "C/ Juan Seba, 1",
  "email": "PedritoPedrito@gmail.com",
  "obras_sociales": [
    { "obra_social_id": 1 },
    { "obra_social_id": 2 }
  ]
}
