### Obtener todas las relaciones obra social-paciente
GET http://localhost:3001/obra_social_paciente

### Obtener una relación obra social-paciente por id_paciente e id_obra_social
GET http://localhost:3001/obra_social_paciente/1/3

### Crear una nueva relación obra social-paciente
POST http://localhost:3001/obra_social_paciente
Content-Type: application/json

{
  "id_paciente":5,
  "id_obra_social": 4
}

### Desactivar una relación obra social-paciente
DELETE http://localhost:3001/obra_social_paciente/1/3

### Activar una relación obra social-paciente
PATCH http://localhost:3001/obra_social_paciente/1/3/activate

### Actualizar parcialmente una relación obra social-paciente
PATCH http://localhost:3001/obra_social_paciente/5/2/update
Content-Type: application/json

// OJO ACA, funciona, envia los datos, los actualiza en BD pero esta capturando el error de no encontrar los primeros datos de busqueda, hay q cambiar la logica del metodo

{
  "id_paciente": 4
}

### Obtener todas los pacientes que tengan una determinada obra social
GET http://localhost:3001/obra_social_paciente/obrasocial/1

### Obtener todas las obras sociales que tiene un determinado paciente
GET http://localhost:3001/obra_social_paciente/paciente/1   
