### Obtener todas las especialidades
GET http://localhost:3001/especialidades

### Obtener una especialidades por su id
GET http://localhost:3001/especialidades/2

### Crear una especialidades
POST http://localhost:3001/especialidades
Content-Type: application/json

{
  "nombre": "Urología"
  
}

### Desactivar una especialidades
DELETE http://localhost:3001/especialidades/4

### Activar una especialidades
PATCH  http://localhost:3001/especialidades/4/activate

### Actualizar una especialidades
PATCH http://localhost:3001/especialidades/4/update
Content-Type: application/json

{
  "nombre": "Dermatología",
  "estado": "1"
}