### Obtener todas las especialidades
GET http://localhost:3001/especialidades

### Obtener una especialidad por su ID
GET http://localhost:3001/especialidades/2

### Crear una especialidad
POST http://localhost:3001/especialidades
Content-Type: application/json

{
  "nombre": "Urología"
}

### Desactivar una especialidad
DELETE http://localhost:3001/especialidades/4

### Activar una especialidad
PATCH  http://localhost:3001/especialidades/4/activate

### Actualizar una especialidad
PATCH http://localhost:3001/especialidades/4/update
Content-Type: application/json

{
  "nombre": "Dermatología",
  "estado": "1"
}

### Buscar especialidades por nombre parcial
GET http://localhost:3001/especialidades/search/med
